### ISSUE TITLE
`yay` fails to clone submodules

### ISSUE THREAD

**Issue by Inityx** [chaotic-aur/pkgbuild-wineasio-git#1]
Currently, installing with `yay -S wineasio-git` fails with the following errors:
```
==> Extracting sources...
  -> Creating working copy of wineasio git repo...
Cloning into 'wineasio'...
done.
  -> Creating working copy of rtaudio git repo...
Cloning into 'rtaudio'...
done.
==> Starting prepare()...
Submodule 'rtaudio' (https://github.com/falkTX/rtaudio.git) registered for path 'rtaudio'
Cloning into '/home/<user>/.cache/yay/wineasio-git/src/wineasio/rtaudio'...
fatal: transport 'file' not allowed
fatal: clone of '/home/<user>/.cache/yay/wineasio-git/src/rtaudio' into submodule path '/home/<user>/.cache/yay/wineasio-git/src/wineasio/rtaudio' failed
Failed to clone 'rtaudio'. Retry scheduled
Cloning into '/home/<user>/.cache/yay/wineasio-git/src/wineasio/rtaudio'...
fatal: transport 'file' not allowed
fatal: clone of '/home/<user>/.cache/yay/wineasio-git/src/rtaudio' into submodule path '/home/<user>/.cache/yay/wineasio-git/src/wineasio/rtaudio' failed
Failed to clone 'rtaudio' a second time, aborting
==> ERROR: A failure occurred in prepare().
    Aborting...
 -> error making: wineasio-git
```

This appears to be a problem with the Git submodule configuration, as noted in [this AUR issue](https://bbs.archlinux.org/viewtopic.php?id=280982) and [this bug report](https://bugs.archlinux.org/task/76255).

https://wiki.archlinux.org/title/VCS_package_guidelines#Git_submodules

**Comment by derkrasseleo** [comment]
This is still an issue

**Comment by PedroHLC** [comment]
Cc @tonylambiris

I'm no longer an arch user, so maybe he as the aur-maintainer can try to take a look.

**Comment by xiota** [comment]
Chaotic AUR build [log](https://builds.garudalinux.org/repos/chaotic-aur/logs/wineasio-git.log).

I notice that a makedepends for `git` is missing.  Could it be that simple?

I made some other changes while poking around... Here's a PR #2
